baseurl = "https://nazakin.net/"
languageCode = "ja"
title = "DUSTBOX"
theme = "casper"
paginate = 5

[params]
  author = "Gomibako"
  description = "世にモンエナのあらんことを"
  hideHUGOSupport = true
  logo = "/icon2.jpg"
  cover = "/cover.jpg"
  googleAnalyticsUserID = "UA-69409018-3"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"
