baseurl = "https://nazakin.net/"
languageCode = "ja"
title = "DUSTBOX"
theme = "casper"

[params]
  author = "dustbox"
  description = "世にモンエナのあらんことを"
  hideHUGOSupport = true
  logo = "/icon.jpg"
  cover = "/cover.jpg"
  twitterName = "____Dustbox____"
  googleAnalyticsUserID = "UA-86535161-1"
