baseurl = "https://nazakin.net/"
LanguageCode = "ja-JP"
defaultContentLanguage = "ja"
title = "DUSTBOX"
theme = "nazakin"
paginate = 12
copyright = "&copy; 2017 DUSTBOX."

[Language]
  Lang = "ja"

[params]
  author = "Gomibako"
  authorname = "Gomibako"
  authorwebsite = "https://nazakin.net/"
  description = "世にモンエナのあらんことを"
  hideHUGOSupport = true
  logo = "icon2.jpg"
  cover = "/cover.jpg"
  googleAnalyticsUserID = "UA-69409018-3"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"

# [outputs]
#  home = ["HTML", "RSS"]
#  post = ["HTML", "RSS"]
#  page = ["HTML", "RSS"]