baseurl = "https://nazakin.net/"
languageCode = "ja"
title = "DUSTBOX"
theme = "casper"

[Params]
name: "dustbox"
thumbnail: "/icon.jpg"
description = "世にモンエナのあらんことを"
hideHUGOSupport = true
logo = "/icon.jpg"
cover = "/cover.jpg"
twitterName = "____Dustbox____"
