# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Nazakin"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://nazakin.net/"
tags = []
features = []
min_version = "0.1"

[author]
  name = "dustbox"
  homepage = "http://nazakin.net/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[outputFormats.JSONFeed]
mediaType = "application/json"